# -*- coding: utf-8 -*-
"""Music creation in colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwlA0lKTkrXAhWurdrzzpnYrbrKOwX2e
"""

# ============================================================
# ORIGINAL Progressive Piano + Electronic Instrumental — ONE CELL COLAB
# - No registration
# - Generates original MIDI + renders to WAV/MP3 via FluidSynth + GM soundfont
# Outputs:
#   /mnt/data/prog_piano_original/prog_piano_original.mid
#   /mnt/data/prog_piano_original/prog_piano_original.wav
#   /mnt/data/prog_piano_original/prog_piano_original.mp3
# ============================================================

import os, random, subprocess, math
import numpy as np

# ---- installs (Colab) ----
subprocess.run(["bash","-lc","apt-get -y update >/dev/null && apt-get -y install fluidsynth ffmpeg fluid-soundfont-gm >/dev/null"], check=False)
subprocess.run(["bash","-lc","pip -q install pretty_midi"], check=False)

import pretty_midi
from IPython.display import Audio, display

out_dir = "/mnt/data/prog_piano_original"
os.makedirs(out_dir, exist_ok=True)

# ----------------------------
# SETTINGS
# ----------------------------
random.seed(11)
np.random.seed(11)

TEMPO = 172  # energetic
pm = pretty_midi.PrettyMIDI(initial_tempo=TEMPO)

# Instruments (General MIDI)
PIANO = 0        # Acoustic Grand Piano
PAD   = 90       # Pad 1 (new age)  (GM2; on GM may map nearby pad)
SYNTH = 81       # Lead 2 (sawtooth) (for subtle electronic layer)
BASS  = 38       # Synth Bass 1 (GM2; if missing, still OK)
PLUCK = 11       # Vibraphone (sparkle layer) or 12 Marimba

piano = pretty_midi.Instrument(program=PIANO, name="Piano Lead")
pad   = pretty_midi.Instrument(program=PAD,   name="Pad")
lead2 = pretty_midi.Instrument(program=SYNTH, name="Synth Lead Layer")
bass  = pretty_midi.Instrument(program=BASS,  name="Synth Bass")
plk   = pretty_midi.Instrument(program=PLUCK, name="Sparkle")

drums = pretty_midi.Instrument(program=0, is_drum=True, name="Drums")

pm.instruments.extend([pad, bass, plk, lead2, piano, drums])

# ----------------------------
# HELPERS
# ----------------------------
def bt(beat):  # beats -> seconds
    return (60.0 / TEMPO) * beat

def add_note(inst, pitch, start_beat, dur_beat, vel=100):
    inst.notes.append(pretty_midi.Note(
        velocity=int(np.clip(vel, 1, 127)),
        pitch=int(np.clip(pitch, 0, 127)),
        start=bt(start_beat),
        end=bt(start_beat + max(0.01, dur_beat)),
    ))

def add_chord(inst, pitches, start_beat, dur_beat, vel=90, strum=0.0):
    for i,p in enumerate(pitches):
        add_note(inst, p, start_beat + i*strum, dur_beat - i*strum, vel)

def note_freq(m):  # not used, but handy if you extend later
    return 440.0 * (2 ** ((m - 69)/12))

# Drum MIDI notes
KICK=36; SNARE=38; HHC=42; HHO=46; CRASH=49; RIDE=51; CLAP=39

def drums_4_4(start, bars, intensity=1.0, hats="16th"):
    beat = start
    for b in range(bars):
        # crash at section start sometimes
        if b == 0 or random.random() < 0.18:
            add_note(drums, CRASH, beat, 0.25, vel=int(95*intensity))

        # hats
        if hats == "16th":
            for i in range(16):
                vel = int((58 if i%2==0 else 45)*intensity)
                add_note(drums, HHC, beat + i*0.25, 0.12, vel=vel)
        else:  # 8th
            for i in range(8):
                vel = int((60 if i%2==0 else 48)*intensity)
                add_note(drums, HHC, beat + i*0.5, 0.14, vel=vel)

        # snare/clap on 2 and 4
        add_note(drums, SNARE, beat + 1.0, 0.2, vel=int(102*intensity))
        add_note(drums, CLAP,  beat + 1.0, 0.2, vel=int(70*intensity))
        add_note(drums, SNARE, beat + 3.0, 0.2, vel=int(102*intensity))
        add_note(drums, CLAP,  beat + 3.0, 0.2, vel=int(70*intensity))

        # kick pattern (driving, slightly syncopated)
        for k in [0.0, 0.75, 1.5, 2.0, 2.75, 3.5]:
            add_note(drums, KICK, beat + k, 0.15, vel=int(110*intensity))

        # occasional open hat lift
        if random.random() < 0.25:
            add_note(drums, HHO, beat + 3.75, 0.2, vel=int(75*intensity))

        beat += 4.0
    return beat

# Tonal material: original progression in A minor -> F -> G -> E (with color tones)
PROG = [
    {"name":"Am(add9)", "root":57, "ch":[57,60,64,71]},  # A3 C4 E4 B4
    {"name":"Fmaj9",    "root":53, "ch":[53,57,60,64,67]},# F3 A3 C4 E4 G4
    {"name":"G6/9",     "root":55, "ch":[55,59,62,64,69]},# G3 B3 D4 E4 A4
    {"name":"E7sus4->E7","root":52,"ch":[52,57,59,62,66]} # E3 A3 B3 D4 F#4 (flavor)
]

def pad_section(start, bars):
    beat = start
    for i in range(bars):
        chord = PROG[i % 4]["ch"]
        # pad long + gentle strum
        add_chord(pad, chord, beat, 4.0, vel=55, strum=0.03)
        # sparkle arps
        arp = chord + [chord[0]+12]
        t = beat
        for k in range(8):
            p = arp[k % len(arp)]
            add_note(plk, p, t, 0.25, vel=45)
            t += 0.5
        beat += 4.0
    return beat

def bass_section(start, bars):
    beat = start
    for i in range(bars):
        root = PROG[i % 4]["root"] - 24  # down 2 octaves
        # driving 8ths with occasional octave jump
        pattern = [0,0,7,0,5,0,7,0]  # semitone offsets (power-ish movement)
        t = beat
        for step, off in enumerate(pattern):
            p = root + off
            vel = 92 if step in [0,4] else 80
            add_note(bass, p, t, 0.45, vel=vel)
            if step in [3,7] and random.random() < 0.4:
                add_note(bass, p+12, t, 0.35, vel=70)
            t += 0.5
        beat += 4.0
    return beat

def piano_comp(start, bars):
    # rhythmic piano stabs + broken chords (keeps it “rock/electro”)
    beat = start
    for i in range(bars):
        chord = PROG[i % 4]["ch"]
        # stabs on strong beats
        for k in [0.0, 1.0, 2.0, 3.0]:
            add_chord(piano, [chord[0], chord[2], chord[3] if len(chord)>3 else chord[2]+7],
                      beat+k, 0.35, vel=92, strum=0.01)
        # broken chord run
        run = chord + [chord[0]+12]
        t = beat + 0.25
        for r in range(12):
            p = run[r % len(run)]
            add_note(piano, p, t, 0.12, vel=70)
            t += 0.25
        beat += 4.0
    return beat

def fast_piano_solo(start, bars):
    # fast 16th-note solo (A minor / A Dorian flavor), wide range
    beat = start
    scale_a = [69,71,72,74,76,77,79,81]  # A4..A5 (A dorian-ish)
    scale_b = [69,72,74,76,79,81]        # pent
    for b in range(bars):
        t = beat
        for i in range(16):  # 16ths in a bar
            src = scale_a if (b % 2 == 0) else scale_b
            p = random.choice(src) + (12 if random.random()<0.55 else 0)
            vel = 110 if i in [0,4,8,12] else 92
            add_note(piano, p, t, 0.22, vel=vel)
            # subtle synth double on accents
            if i in [0,4,8,12] and random.random()<0.7:
                add_note(lead2, p, t, 0.22, vel=60)
            t += 0.25
        # end-of-phrase high hit
        if b % 2 == 1:
            add_note(piano, 93 if random.random()<0.5 else 95, beat+3.0, 1.0, vel=120)
            add_note(lead2,  93 if random.random()<0.5 else 95, beat+3.0, 1.0, vel=62)
        beat += 4.0
    return beat

def breakdown(start, bars):
    # half-time + airy pad + piano arps
    beat = start
    for i in range(bars):
        chord = PROG[i % 4]["ch"]
        add_chord(pad, chord, beat, 4.0, vel=52, strum=0.05)
        # half-time drums
        add_note(drums, KICK, beat+0.0, 0.2, vel=95)
        add_note(drums, SNARE, beat+2.0, 0.2, vel=95)
        for h in range(8):
            add_note(drums, HHC, beat + h*0.5, 0.12, vel=40)
        # piano arpeggio (triplet-ish feel with 0.333 beats)
        arp = chord + [chord[0]+12]
        t = beat
        for k in range(12):
            p = arp[k % len(arp)]
            add_note(piano, p, t, 0.15, vel=62)
            t += (4.0/12.0)
        beat += 4.0
    return beat

def ending(start, bars):
    beat = start
    for i in range(bars):
        chord = PROG[i % 4]["ch"]
        add_chord(piano, chord, beat, 4.0, vel=95, strum=0.02)
        add_chord(pad, chord, beat, 4.0, vel=50, strum=0.05)
        # big drums
        add_note(drums, CRASH, beat, 0.25, vel=110)
        drums_4_4(beat, 1, intensity=1.15, hats="8th")
        # bass root sustain
        add_note(bass, PROG[i % 4]["root"]-24, beat, 4.0, vel=92)
        beat += 4.0
    # final ring
    add_chord(piano, [57,60,64,69,72], beat, 6.0, vel=115, strum=0.02)  # Am-ish
    add_chord(pad,   [57,60,64,69,72], beat, 6.0, vel=55,  strum=0.06)
    add_note(drums, CRASH, beat, 0.25, vel=120)
    add_note(bass, 33, beat, 6.0, vel=95)  # A1
    return beat + 6.0

# ----------------------------
# ARRANGEMENT (Original)
# ----------------------------
cur = 0.0

# Intro (4 bars): pad + light hats
pad_section(cur, 4)
for i in range(4):
    add_note(drums, HHC, cur + i*4.0 + 0.0, 0.12, vel=35)
    add_note(drums, HHC, cur + i*4.0 + 2.0, 0.12, vel=35)
cur += 16.0

# Main groove (8 bars): full drums + bass + piano comp
drums_4_4(cur, 8, intensity=1.05, hats="16th")
pad_section(cur, 8)
bass_section(cur, 8)
piano_comp(cur, 8)
cur += 32.0

# Build (4 bars): louder, more stabs
drums_4_4(cur, 4, intensity=1.15, hats="16th")
pad_section(cur, 4)
bass_section(cur, 4)
piano_comp(cur, 4)
cur += 16.0

# Fast piano solo (12 bars)
drums_4_4(cur, 12, intensity=1.18, hats="16th")
pad_section(cur, 12)
bass_section(cur, 12)
cur = fast_piano_solo(cur, 12)

# Breakdown (6 bars)
cur = breakdown(cur, 6)

# Final solo sprint (6 bars)
drums_4_4(cur, 6, intensity=1.22, hats="16th")
pad_section(cur, 6)
bass_section(cur, 6)
cur = fast_piano_solo(cur, 6)

# Ending (4 bars + ring)
cur = ending(cur, 4)

# ----------------------------
# WRITE MIDI
# ----------------------------
midi_path = os.path.join(out_dir, "prog_piano_original.mid")
pm.write(midi_path)

# ----------------------------
# RENDER AUDIO
# ----------------------------
sf2_candidates = [
    "/usr/share/sounds/sf2/FluidR3_GM.sf2",
    "/usr/share/sounds/sf2/FluidR3_GM2-2.sf2",
    "/usr/share/sounds/sf2/FluidR3_GM2.sf2",
]
sf2 = next((p for p in sf2_candidates if os.path.exists(p)), None)
if sf2 is None:
    raise FileNotFoundError("No GM soundfont found. The install may have failed.")

wav_path = os.path.join(out_dir, "prog_piano_original.wav")
mp3_path = os.path.join(out_dir, "prog_piano_original.mp3")

subprocess.run(["bash","-lc", f'fluidsynth -ni "{sf2}" "{midi_path}" -F "{wav_path}" -r 44100 >/dev/null'], check=True)
subprocess.run(["bash","-lc", f'ffmpeg -y -i "{wav_path}" -codec:a libmp3lame -qscale:a 2 "{mp3_path}" >/dev/null'], check=False)

print("✅ Done. Files:")
print(midi_path)
print(wav_path)
print(mp3_path)

display(Audio(wav_path))

# ============================================================
# ORIGINAL Uplifting Trance (strings + build + drop) — ONE CELL COLAB
# - No registration
# - Generates original MIDI + renders WAV/MP3 via FluidSynth (free GM soundfont)
# Outputs:
#   /mnt/data/uplifting_trance_original/uplifting_trance_original.mid
#   /mnt/data/uplifting_trance_original/uplifting_trance_original.wav
#   /mnt/data/uplifting_trance_original/uplifting_trance_original.mp3
# ============================================================

import os, random, subprocess
import numpy as np

subprocess.run(["bash","-lc","apt-get -y update >/dev/null && apt-get -y install fluidsynth ffmpeg fluid-soundfont-gm >/dev/null"], check=False)
subprocess.run(["bash","-lc","pip -q install pretty_midi"], check=False)

import pretty_midi
from IPython.display import Audio, display

out_dir = "/mnt/data/uplifting_trance_original"
os.makedirs(out_dir, exist_ok=True)

random.seed(22)
np.random.seed(22)

TEMPO = 138
pm = pretty_midi.PrettyMIDI(initial_tempo=TEMPO)

# GM programs (approximate)
STRINGS = 48      # String Ensemble 1
PAD     = 89      # Pad 2 (warm) / may vary
LEAD    = 81      # Lead 2 (sawtooth)
PLUCK   = 87      # Lead 8 (bass+lead) / alt pluck-ish
BASS    = 38      # Synth Bass 1 (may vary but ok)
HIT     = 55      # Synth Voice / for impacts (optional)

strings = pretty_midi.Instrument(program=STRINGS, name="Strings")
pad     = pretty_midi.Instrument(program=PAD,     name="Pad")
lead    = pretty_midi.Instrument(program=LEAD,    name="Lead")
pluck   = pretty_midi.Instrument(program=PLUCK,   name="Pluck/Arp")
bass    = pretty_midi.Instrument(program=BASS,    name="Bass")
fxhit   = pretty_midi.Instrument(program=HIT,     name="FX Hit")
drums   = pretty_midi.Instrument(program=0, is_drum=True, name="Drums")

pm.instruments.extend([pad, strings, bass, pluck, lead, fxhit, drums])

def bt(beat):  # beats -> seconds
    return (60.0 / TEMPO) * beat

def add_note(inst, pitch, start_beat, dur_beat, vel=100):
    inst.notes.append(pretty_midi.Note(
        velocity=int(np.clip(vel,1,127)),
        pitch=int(np.clip(pitch,0,127)),
        start=bt(start_beat),
        end=bt(start_beat+max(0.01,dur_beat))
    ))

def add_chord(inst, pitches, start_beat, dur_beat, vel=85, strum=0.0):
    for i,p in enumerate(pitches):
        add_note(inst, p, start_beat+i*strum, dur_beat-i*strum, vel)

# Drum notes
KICK=36; SNARE=38; CLAP=39; HHC=42; HHO=46; CRASH=49

def drums_4onfloor(start, bars, intensity=1.0, hats16=True, clap=True):
    beat = start
    for b in range(bars):
        # crash at section start
        if b == 0:
            add_note(drums, CRASH, beat, 0.25, vel=int(105*intensity))
        # kick each beat
        for k in [0,1,2,3]:
            add_note(drums, KICK, beat+k, 0.12, vel=int(118*intensity))
        # clap/snare on 2 and 4
        if clap:
            add_note(drums, CLAP, beat+1.0, 0.12, vel=int(95*intensity))
            add_note(drums, CLAP, beat+3.0, 0.12, vel=int(95*intensity))
        add_note(drums, SNARE, beat+1.0, 0.12, vel=int(78*intensity))
        add_note(drums, SNARE, beat+3.0, 0.12, vel=int(78*intensity))
        # hats
        if hats16:
            for i in range(16):
                vel = int((58 if i%2==0 else 44)*intensity)
                add_note(drums, HHC, beat+i*0.25, 0.08, vel=vel)
        else:
            for i in range(8):
                vel = int((60 if i%2==0 else 46)*intensity)
                add_note(drums, HHC, beat+i*0.5, 0.10, vel=vel)
        # occasional open hat
        if random.random() < 0.25:
            add_note(drums, HHO, beat+3.5, 0.18, vel=int(65*intensity))
        beat += 4.0
    return beat

def snare_roll_build(start, bars):
    # rising snare rate: 8ths -> 16ths -> 32nds feel (approx)
    beat = start
    for b in range(bars):
        # 8th hits
        for i in range(8):
            add_note(drums, SNARE, beat+i*0.5, 0.10, vel=55 + b*6)
        beat += 4.0
    return beat

# --- Harmony (ORIGINAL): D minor -> Bb -> F -> C (uplifting minor feel)
# Chords in mid register
PROG = [
    {"root":50, "ch":[50,53,57,60]},     # Dm (D3 F3 A3 C4)
    {"root":46, "ch":[46,50,53,57]},     # Bb (Bb2 D3 F3 A3)
    {"root":53, "ch":[53,57,60,64]},     # F  (F3 A3 C4 E4)
    {"root":48, "ch":[48,52,55,60]}      # C  (C3 E3 G3 C4)
]

def pad_strings_section(start, bars, strings_vel=70, pad_vel=50):
    beat = start
    for i in range(bars):
        chord = PROG[i % 4]["ch"]
        add_chord(pad, chord, beat, 4.0, vel=pad_vel, strum=0.02)
        add_chord(strings, [p+12 for p in chord], beat, 4.0, vel=strings_vel, strum=0.01)
        beat += 4.0
    return beat

def bass_section(start, bars, driving=True, vel=95):
    beat = start
    for i in range(bars):
        r = PROG[i % 4]["root"] - 24  # down
        if driving:
            # 1/8 pumping
            t = beat
            for k in range(8):
                add_note(bass, r, t, 0.45, vel=vel if k%2==0 else vel-10)
                t += 0.5
        else:
            add_note(bass, r, beat, 4.0, vel=vel-12)
        beat += 4.0
    return beat

def arp_section(start, bars, vel=70):
    beat = start
    for i in range(bars):
        chord = PROG[i % 4]["ch"]
        arp = chord + [chord[1]+12, chord[2]+12, chord[3]+12]
        t = beat
        # 16th arpeggio
        for k in range(16):
            p = arp[k % len(arp)]
            add_note(pluck, p+12, t, 0.20, vel=vel if k%4!=0 else vel+8)
            t += 0.25
        beat += 4.0
    return beat

def lead_melody(start, bars, vel=92):
    beat = start
    # simple uplifting motif in D minor scale region
    scale = [74,76,77,79,81,82,84]  # D5..C6 (D natural minor-ish)
    motif = [0,2,4,2,5,4,2,1,0,2,4,5,4,2,1,0]  # indices in scale
    for b in range(bars):
        t = beat
        for i in range(16):
            p = scale[motif[i] % len(scale)]
            # phrase accents
            v = vel+15 if i in [0,4,8,12] else vel
            add_note(lead, p, t, 0.22, vel=v)
            t += 0.25
        # long note tail
        add_note(lead, scale[4] if b%2==0 else scale[6], beat+3.0, 1.0, vel=110)
        beat += 4.0
    return beat

def impact(start_beat):
    # crash + hit
    add_note(drums, CRASH, start_beat, 0.25, vel=120)
    add_chord(fxhit, [84,88,91], start_beat, 1.0, vel=70, strum=0.0)

# ----------------------------
# ARRANGEMENT
# ----------------------------
cur = 0.0

# 1) Intro (8 bars): pads+strings only, light hats
cur = pad_strings_section(cur, 8, strings_vel=60, pad_vel=45)
# light hats
t = 0.0
for bar in range(8):
    for i in range(8):
        add_note(drums, HHC, t + bar*4.0 + i*0.5, 0.08, vel=35)
cur = 32.0

# 2) Groove (8 bars): kick + bass + arp + more strings
impact(cur)
cur = drums_4onfloor(cur, 8, intensity=1.0, hats16=False, clap=False)
pad_strings_section(32.0, 8, strings_vel=68, pad_vel=48)
bass_section(32.0, 8, driving=True, vel=90)
arp_section(32.0, 8, vel=62)
cur = 64.0

# 3) Build (8 bars): add clap, more hats, snare build in last 4 bars
impact(cur)
cur = drums_4onfloor(cur, 4, intensity=1.05, hats16=True, clap=True)
pad_strings_section(64.0, 4, strings_vel=75, pad_vel=52)
bass_section(64.0, 4, driving=True, vel=95)
arp_section(64.0, 4, vel=72)

# build-roll
snare_roll_build(80.0, 4)
# reduce kick last 2 bars for tension
for n in list(drums.notes):
    # delete kicks between beats 88..96 (last 2 bars of build)
    if n.pitch == KICK and bt(88.0) <= n.start < bt(96.0):
        drums.notes.remove(n)

pad_strings_section(80.0, 4, strings_vel=82, pad_vel=56)
arp_section(80.0, 4, vel=80)
cur = 96.0

# 4) Drop (16 bars): full groove + lead melody + big strings
impact(cur)
cur = drums_4onfloor(cur, 16, intensity=1.12, hats16=True, clap=True)
pad_strings_section(96.0, 16, strings_vel=92, pad_vel=55)
bass_section(96.0, 16, driving=True, vel=104)
arp_section(96.0, 16, vel=78)
lead_melody(96.0, 16, vel=92)
cur = 160.0

# 5) Outro (8 bars): remove lead, keep pads/strings, hats fade
impact(cur)
cur = drums_4onfloor(cur, 4, intensity=0.95, hats16=False, clap=False)
pad_strings_section(160.0, 8, strings_vel=70, pad_vel=48)
bass_section(160.0, 8, driving=False, vel=80)
arp_section(160.0, 4, vel=55)

# final ring
add_chord(strings, [62,65,69,74,77], 192.0, 8.0, vel=85, strum=0.01)
add_chord(pad,     [50,53,57,62],     192.0, 8.0, vel=50, strum=0.03)
add_note(drums, CRASH, 192.0, 0.25, vel=110)

# ----------------------------
# WRITE MIDI
# ----------------------------
midi_path = os.path.join(out_dir, "uplifting_trance_original.mid")
pm.write(midi_path)

# ----------------------------
# RENDER AUDIO
# ----------------------------
sf2_candidates = [
    "/usr/share/sounds/sf2/FluidR3_GM.sf2",
    "/usr/share/sounds/sf2/FluidR3_GM2-2.sf2",
    "/usr/share/sounds/sf2/FluidR3_GM2.sf2",
]
sf2 = next((p for p in sf2_candidates if os.path.exists(p)), None)
if sf2 is None:
    raise FileNotFoundError("No GM soundfont found. (fluid-soundfont-gm install may have failed)")

wav_path = os.path.join(out_dir, "uplifting_trance_original.wav")
mp3_path = os.path.join(out_dir, "uplifting_trance_original.mp3")

subprocess.run(["bash","-lc", f'fluidsynth -ni "{sf2}" "{midi_path}" -F "{wav_path}" -r 44100 >/dev/null'], check=True)
subprocess.run(["bash","-lc", f'ffmpeg -y -i "{wav_path}" -codec:a libmp3lame -qscale:a 2 "{mp3_path}" >/dev/null'], check=False)

print("✅ Done. Files:")
print(midi_path)
print(wav_path)
print(mp3_path)
display(Audio(wav_path))

# =========================
# FIXED: Original "happy classical" generator (Mozart/Vivaldi-inspired, NOT a copy)
# Output: /content/classical_happy/classical_happy.mid .wav .mp3
# =========================

!pip -q install music21
!apt-get -qq update
!apt-get -qq install -y fluidsynth ffmpeg fluid-soundfont-gm

import os, random
from music21 import stream, note, chord, meter, tempo, key, instrument, dynamics, scale

OUT_DIR = "/content/classical_happy"
os.makedirs(OUT_DIR, exist_ok=True)

MID_PATH = os.path.join(OUT_DIR, "classical_happy.mid")
WAV_PATH = os.path.join(OUT_DIR, "classical_happy.wav")
MP3_PATH = os.path.join(OUT_DIR, "classical_happy.mp3")

# --------- Style ----------
STYLE = "mozart"   # "mozart" (piano + alberti) or "vivaldi" (violin + strings pulse)
SEED = 7
random.seed(SEED)

# --------- Global setup ----------
TONIC = "C"
MODE  = "major"
BPM   = 132 if STYLE == "vivaldi" else 124
TIME_SIGNATURE = "4/4"
BARS = 32

k = key.Key(TONIC, MODE)
sc = scale.MajorScale(k.tonic)

# Common upbeat progressions (original sequencing)
PROG = [
    ("I", "V", "vi", "IV"),
    ("I", "IV", "V", "I"),
    ("ii", "V", "I", "I"),
    ("I", "V", "I", "V"),
]

ROMAN_TO_DEGREES = {
    "I":  [1,3,5],
    "ii": [2,4,6],
    "IV": [4,6,1],
    "V":  [5,7,2],
    "vi": [6,1,3],
}

def scale_pitch(deg:int, octave:int):
    # deg 1..7, safe always
    deg = ((deg - 1) % 7) + 1
    p = sc.pitchFromDegree(deg)
    p.octave = octave
    return p

def triad_pitches(roman:str, octave:int):
    degs = ROMAN_TO_DEGREES[roman]
    return [scale_pitch(d, octave) for d in degs]

def flatten_progression(bars:int):
    seq = []
    while len(seq) < bars:
        for group in PROG:
            seq.extend(group)
            if len(seq) >= bars:
                break
    # end with cadence V -> I
    if bars >= 2:
        seq[-2] = "V"
        seq[-1] = "I"
    return seq[:bars]

roman_seq = flatten_progression(BARS)

# --------- Accompaniment ----------
def add_alberti_bass(part, roman_seq):
    # Alberti: low-high-mid-high as eighth notes
    for roman in roman_seq:
        tps = triad_pitches(roman, octave=3)
        low, mid, high = tps[0], tps[1], tps[2]
        pattern = [low, high, mid, high] * 2
        for p in pattern:
            n = note.Note(p)
            n.quarterLength = 0.5
            n.volume.velocity = 52
            part.append(n)

def add_string_pulse(part, roman_seq):
    # Vivaldi-like pulse: 8ths on chord tones
    for roman in roman_seq:
        tps = triad_pitches(roman, octave=4)
        seq = [tps[0], tps[2], tps[1], tps[2]] * 2
        for p in seq:
            n = note.Note(p)
            n.quarterLength = 0.5
            n.volume.velocity = 60
            part.append(n)

# --------- Melody (robust, always in-scale) ----------
def add_melody(part, roman_seq):
    # Rule: strong beats = chord tones; weak beats = neighbor/passing
    for i, roman in enumerate(roman_seq):
        tps = triad_pitches(roman, octave=5)
        chord_degs = ROMAN_TO_DEGREES[roman]  # 3 degrees

        if STYLE == "vivaldi":
            # 8 eighth-notes, bright arpeggio pattern with tiny variations
            base = [tps[0], tps[2], tps[1], tps[2], tps[0], tps[2], tps[1], tps[2]]
            if i % 4 == 2:
                # small sequence move using scale degrees (still safe)
                d = chord_degs[0]
                base[1] = scale_pitch(d+1, 5)
                base[5] = scale_pitch(d+2, 5)
            for p in base:
                n = note.Note(p)
                n.quarterLength = 0.5
                n.volume.velocity = 82
                part.append(n)
        else:
            # 4 quarter-notes: chord tone, neighbor, chord tone, cadence-ish
            d0 = chord_degs[0]
            d2 = chord_degs[2]
            neighbor = d0 + (1 if i % 2 == 0 else -1)

            motif = [
                scale_pitch(d0, 5),
                scale_pitch(neighbor, 5),
                scale_pitch(d2, 5),
                scale_pitch(d0, 5),
            ]

            # occasional upbeat jump
            if i % 8 == 4:
                motif[2] = scale_pitch(d2+2, 5)

            for p in motif:
                n = note.Note(p)
                n.quarterLength = 1.0
                n.volume.velocity = 78
                part.append(n)

# --------- Build score ----------
score = stream.Score()
score.append(tempo.MetronomeMark(number=BPM))
score.append(meter.TimeSignature(TIME_SIGNATURE))
score.append(k)

mel = stream.Part()
acc = stream.Part()

if STYLE == "vivaldi":
    mel.insert(0, instrument.Violin())
    acc.insert(0, instrument.StringEnsemble())
else:
    mel.insert(0, instrument.Piano())
    acc.insert(0, instrument.Piano())

mel.append(dynamics.Dynamic('mf'))
acc.append(dynamics.Dynamic('mp'))

add_melody(mel, roman_seq)
if STYLE == "vivaldi":
    add_string_pulse(acc, roman_seq)
else:
    add_alberti_bass(acc, roman_seq)

score.insert(0, mel)
score.insert(0, acc)

# --------- Export MIDI ----------
score.write("midi", fp=MID_PATH)
print("Saved MIDI:", MID_PATH)

# --------- Render with FluidSynth (SoundFont) ----------
SF2 = "/usr/share/sounds/sf2/FluidR3_GM.sf2"
assert os.path.exists(SF2), "SoundFont missing; apt install failed."

!fluidsynth -ni "{SF2}" "{MID_PATH}" -F "{WAV_PATH}" -r 44100 >/dev/null 2>&1
!ffmpeg -y -loglevel error -i "{WAV_PATH}" -b:a 192k "{MP3_PATH}"

print("Saved WAV:", WAV_PATH)
print("Saved MP3:", MP3_PATH)
print("Folder:", OUT_DIR)

from IPython.display import Audio, display
display(Audio(WAV_PATH))

# =========================
# CBT MEDITATION v3 — 1 minute, MORE HUMAN voice (Edge Neural TTS) + ocean background
# NO SSML (so it will never read tags). We create pauses by splitting text into chunks + silence.
# Outputs: /mnt/data/meditation_project/cbt_meditation_final_v3.wav/.mp3
# =========================

import os, subprocess
import numpy as np
from scipy.signal import butter, lfilter
from pydub import AudioSegment
from IPython.display import Audio, display
import asyncio

# Install
subprocess.run(["bash","-lc","apt-get -y update >/dev/null && apt-get -y install ffmpeg >/dev/null"], check=False)
subprocess.run(["bash","-lc","pip -q install edge-tts numpy scipy pydub"], check=False)

import edge_tts

SR = 44100
DURATION_S = 60
out_dir = "/mnt/data/meditation_project"
os.makedirs(out_dir, exist_ok=True)

VOICE_WAV = os.path.join(out_dir, "voice_v3.wav")
BG_WAV    = os.path.join(out_dir, "ocean_bg.wav")
FINAL_WAV = os.path.join(out_dir, "cbt_meditation_final_v3.wav")
FINAL_MP3 = os.path.join(out_dir, "cbt_meditation_final_v3.mp3")

# -------- 1) Human-like voice (pick one) --------
# Good options:
# "en-US-JennyNeural" (female), "en-US-GuyNeural" (male),
# "en-GB-SoniaNeural" (female UK), "en-GB-RyanNeural" (male UK)
VOICE_NAME = "en-US-JennyNeural"
RATE = "-10%"   # try "-5%" or "0%" if you want faster
PITCH = "-2Hz"  # try "0Hz" if you want brighter

# -------- 2) CBT meditation chunks + pauses (no SSML) --------
# Each tuple: (text_to_speak, silence_ms_after)
chunks = [
    ("Find a comfortable position.", 450),
    ("Breathe in slowly… and breathe out.", 650),
    ("Now do a quick CBT check.", 400),

    ("Catch it.", 250),
    ("What is the main thought bothering you right now?", 850),
    ("Say it in one short sentence.", 850),

    ("Check it.", 250),
    ("Is that thought a fact, or a guess?", 700),
    ("What evidence supports it?", 750),
    ("What evidence goes against it?", 900),

    ("Change it.", 250),
    ("Create a balanced thought—realistic and kind.", 750),
    ("Repeat: This is hard, and I can handle it step by step.", 850),
    ("Repeat: I can choose one helpful action now.", 850),

    ("If your mind drifts, gently return to the breath.", 650),
    ("In… and out.", 850),

    ("To finish, choose one tiny next step you will take after this.", 900),
    ("One small step is enough.", 500),
]

async def tts_chunk_to_wav(text, wav_path):
    # edge-tts saves mp3; convert to wav at SR mono
    tmp_mp3 = wav_path.replace(".wav", ".mp3")
    # Use SSML prosody without tags by embedding only in communicate? -> we avoid SSML entirely.
    # Instead, we use edge-tts CLI style params via Communicate's rate/pitch fields:
    communicate = edge_tts.Communicate(text=text, voice=VOICE_NAME, rate=RATE, pitch=PITCH)
    await communicate.save(tmp_mp3)
    subprocess.run(["bash","-lc", f'ffmpeg -y -loglevel error -i "{tmp_mp3}" -ar {SR} -ac 1 "{wav_path}"'], check=False)

async def build_voice():
    voice = AudioSegment.silent(duration=0, frame_rate=SR)
    for i, (txt, pause_ms) in enumerate(chunks):
        wav_i = os.path.join(out_dir, f"chunk_{i:02d}.wav")
        await tts_chunk_to_wav(txt, wav_i)
        seg = AudioSegment.from_wav(wav_i)
        voice += seg + AudioSegment.silent(duration=pause_ms, frame_rate=SR)
    return voice

voice = asyncio.run(build_voice())

# Fit to exactly 60s
target_ms = DURATION_S * 1000
if len(voice) < target_ms:
    voice = voice + AudioSegment.silent(duration=(target_ms - len(voice)), frame_rate=SR)
else:
    voice = voice[:target_ms]

voice.export(VOICE_WAV, format="wav")

# -------- 3) Ocean background (same approach as before; synthesized) --------
def lowpass(x, cutoff=2600, sr=SR, order=4):
    b, a = butter(order, cutoff/(sr/2), btype="low")
    return lfilter(b, a, x)

def to_audiosegment(x, sr=SR):
    x = np.clip(x, -1, 1)
    pcm = (x * 32767).astype(np.int16).tobytes()
    return AudioSegment(data=pcm, sample_width=2, frame_rate=sr, channels=1)

def make_ocean(duration_s, sr=SR, seed=3):
    rng = np.random.default_rng(seed)
    n = int(duration_s * sr)
    t = np.arange(n) / sr

    noise = rng.normal(0, 1, n).astype(np.float32)
    hiss = lowpass(noise, cutoff=2400, sr=sr, order=4)
    hiss = hiss / (np.std(hiss) + 1e-9)

    swell1 = 0.5 * (1 - np.cos(2*np.pi*(1/7.5)*t))
    swell2 = 0.5 * (1 - np.cos(2*np.pi*(1/16.0)*t))
    env = 0.20 + 0.55*(swell1**1.6) + 0.20*(swell2**1.8)

    rumble = 0.015*np.sin(2*np.pi*55*t) + 0.008*np.sin(2*np.pi*72*t)

    x = (0.20 * env * hiss + rumble).astype(np.float32)
    x = lowpass(x, cutoff=2600, sr=sr, order=4)
    x = x / (np.max(np.abs(x)) + 1e-9) * 0.95
    return x

bg = make_ocean(DURATION_S, SR)
bg_seg = to_audiosegment(bg, SR).fade_in(2500).fade_out(2500).apply_gain(-18)
bg_seg.export(BG_WAV, format="wav")

# -------- 4) Mix --------
voice = AudioSegment.from_wav(VOICE_WAV).apply_gain(-2).fade_in(300).fade_out(900)
bg    = AudioSegment.from_wav(BG_WAV)

final = bg.overlay(voice, position=0).fade_in(1200).fade_out(1800)
final.export(FINAL_WAV, format="wav")
subprocess.run(["bash","-lc", f'ffmpeg -y -loglevel error -i "{FINAL_WAV}" -codec:a libmp3lame -qscale:a 2 "{FINAL_MP3}"'], check=False)

print("✅ Done. Files:")
print(FINAL_WAV)
print(FINAL_MP3)
display(Audio(FINAL_WAV))

# =========================
# RAP SONG v5 — longer: ~10s intro (no words) + slower vocals + ~10s outro (no words)
# No registration. Single cell. Outputs rap_song_final_v5.wav/.mp3
# =========================

import os, subprocess
import numpy as np
from scipy.signal import butter, lfilter
from pydub import AudioSegment
from IPython.display import Audio, display

subprocess.run(["bash","-lc","apt-get -y update >/dev/null && apt-get -y install ffmpeg espeak-ng >/dev/null"], check=False)
subprocess.run(["bash","-lc","pip -q install numpy scipy pydub"], check=False)

SR = 44100
BPM = 90
BEATS_PER_BAR = 4

# 10s ≈ 4 bars at 90 BPM (4*2.666=10.666s)
INTRO_BARS = 4
OUTRO_BARS = 4

# We keep your story lines, but give each one 4 bars so it can be spoken slower
BARS_PER_LINE = 4
lyrics_lines = [
    "We walked in stressed, you snapped quick, I snapped back, the room went cold, [[slnc 170]] "
    "I felt disrespected, you felt unseen, and both of us got bold, [[slnc 170]] "
    "my pride tried to drive the conversation, like it wanted full control.",

    "I caught my breath, I lowered my voice, I said: wait, let me be clear, [[slnc 170]] "
    "this is what I felt in that moment, and why it hit so near, [[slnc 170]] "
    "then I asked you gently: what were you needing, right here?",

    "You said: I felt ignored for weeks, like my effort didn't count, [[slnc 170]] "
    "I said: I hear you, and I'm sorry, I can see what that amounts, [[slnc 170]] "
    "we put the problem on the table, not our names, not our accounts.",

    "We made two options, then three, we chose the one that fit us both, [[slnc 170]] "
    "we set one boundary: no attacks, and one promise: keep it growth, [[slnc 170]] "
    "and if it heats up, we pause ten minutes, then return, not ghost.",

    "Now the same room feels lighter, like the air got a new shape, [[slnc 170]] "
    "conflict didn't break the bond, it taught us how to escape, [[slnc 170]] "
    "peace isn't silence, it's brave respect, and the patience to repair."
]

NUM_LINES = len(lyrics_lines)
VOCAL_BARS = NUM_LINES * BARS_PER_LINE
TOTAL_BARS = INTRO_BARS + VOCAL_BARS + OUTRO_BARS

beat_s = 60.0 / BPM
bar_s  = beat_s * BEATS_PER_BAR
song_ms = int(TOTAL_BARS * bar_s * 1000)

out_dir = "/mnt/data/rap_project"
os.makedirs(out_dir, exist_ok=True)

# ---- helpers ----
def to_audiosegment(x, sr=SR):
    x = np.clip(x, -1, 1)
    pcm = (x * 32767).astype(np.int16).tobytes()
    return AudioSegment(data=pcm, sample_width=2, frame_rate=sr, channels=1)

def env_exp(n, decay=0.03, sr=SR):
    t = np.arange(n)/sr
    return np.exp(-t/decay)

def lowpass(x, cutoff=8000, sr=SR, order=4):
    b,a = butter(order, cutoff/(sr/2), btype="low")
    return lfilter(b,a,x)

def highpass(x, cutoff=200, sr=SR, order=4):
    b,a = butter(order, cutoff/(sr/2), btype="high")
    return lfilter(b,a,x)

def sine(freq, dur_s, amp=0.6, sr=SR):
    n = int(dur_s*sr)
    t = np.arange(n)/sr
    return (amp*np.sin(2*np.pi*freq*t)).astype(np.float32)

def noise(dur_s, amp=0.4, sr=SR):
    n = int(dur_s*sr)
    return (amp*np.random.uniform(-1,1,n)).astype(np.float32)

def normalize(x, target=0.95):
    m = np.max(np.abs(x)) + 1e-9
    return (x/m*target).astype(np.float32)

def overlay(base: AudioSegment, layer: AudioSegment, position_ms=0, gain_db=0.0):
    return base.overlay(layer + gain_db, position=position_ms)

def ms(t_s): return int(t_s*1000)

# ---- drum sounds ----
def kick():
    dur = 0.18
    n = int(dur*SR)
    t = np.arange(n)/SR
    f0, f1 = 90.0, 45.0
    f = f0 * (f1/f0) ** (t/dur)
    phase = 2*np.pi*np.cumsum(f)/SR
    x = np.sin(phase) * env_exp(n, decay=0.07)
    x = lowpass(x, cutoff=900)
    return normalize(x, 0.9)

def snare():
    dur = 0.15
    n = int(dur*SR)
    x = noise(dur, amp=0.8)
    x = highpass(x, cutoff=1200)
    x = x * env_exp(n, decay=0.05)
    x += sine(180, dur, amp=0.15) * env_exp(n, decay=0.05)
    return normalize(x, 0.8)

def hat():
    dur = 0.06
    n = int(dur*SR)
    x = noise(dur, amp=0.35)
    x = highpass(x, cutoff=6000)
    x = x * env_exp(n, decay=0.02)
    return normalize(x, 0.5)

KICK = to_audiosegment(kick())
SNARE = to_audiosegment(snare())
HAT = to_audiosegment(hat())

# ---- build drums for TOTAL_BARS ----
drums = AudioSegment.silent(duration=song_ms, frame_rate=SR)
for bar in range(TOTAL_BARS):
    bar_start = bar * bar_s

    kicks = [0.0, 2.0]
    if bar % 2 == 1:
        kicks.append(3.5)
    for b in kicks:
        drums = overlay(drums, KICK, position_ms=ms(bar_start + b*beat_s), gain_db=0)

    for b in [1.0, 3.0]:
        drums = overlay(drums, SNARE, position_ms=ms(bar_start + b*beat_s), gain_db=-1)

    for i in range(8):
        b = i * 0.5
        gain = -6 if (i % 2 == 0) else -8
        drums = overlay(drums, HAT, position_ms=ms(bar_start + b*beat_s), gain_db=gain)

# ---- bass + pad for TOTAL_BARS ----
def note_freq(midi_note):
    return 440.0 * (2 ** ((midi_note - 69)/12))

bass_roots = [45, 41, 43, 40]  # A2 F2 G2 E2
chords = [
    [57, 60, 64],  # Am
    [53, 57, 60],  # F
    [55, 59, 62],  # G
    [52, 55, 59],  # Em-ish
]

def bass_hit(freq, dur_s, amp=0.6):
    x = sine(freq, dur_s, amp=amp)
    x = lowpass(x, cutoff=250)
    x *= env_exp(len(x), decay=0.12)
    return x.astype(np.float32)

def chord_pad(freqs, dur_s, amp=0.18):
    n = int(dur_s*SR)
    t = np.arange(n)/SR
    x = np.zeros(n, dtype=np.float32)
    for f in freqs:
        for k, a in [(1,1.0),(2,0.35),(3,0.2)]:
            x += (amp*a)*np.sin(2*np.pi*(f*k)*t)
    x = lowpass(x, cutoff=1800)
    fade = np.ones(n, dtype=np.float32)
    fi = int(0.08*n); fo = int(0.12*n)
    fade[:fi] = np.linspace(0,1,fi)
    fade[-fo:] = np.linspace(1,0,fo)
    x *= fade
    return normalize(x, 0.6)

inst = AudioSegment.silent(duration=song_ms, frame_rate=SR)
for bar in range(TOTAL_BARS):
    idx = bar % 4
    root = bass_roots[idx]
    chord = chords[idx]

    b1 = bass_hit(note_freq(root), beat_s*0.6, amp=0.65)
    b3 = bass_hit(note_freq(root), beat_s*0.6, amp=0.60)

    bass_seg = AudioSegment.silent(duration=int(bar_s*1000), frame_rate=SR)
    bass_seg = overlay(bass_seg, to_audiosegment(b1), position_ms=0, gain_db=-1)
    bass_seg = overlay(bass_seg, to_audiosegment(b3), position_ms=ms(2*beat_s), gain_db=-1)

    freqs = [note_freq(n) for n in chord]
    pad_seg = to_audiosegment(chord_pad(freqs, bar_s, amp=0.14))

    bar_seg = AudioSegment.silent(duration=int(bar_s*1000), frame_rate=SR)
    bar_seg = overlay(bar_seg, pad_seg, position_ms=0, gain_db=-9)
    bar_seg = overlay(bar_seg, bass_seg, position_ms=0, gain_db=0)

    inst = overlay(inst, bar_seg, position_ms=ms(bar*bar_s), gain_db=0)

instrumental = inst.overlay(drums, position=0) - 1
instrumental_wav = os.path.join(out_dir, "instrumental_v5.wav")
instrumental.export(instrumental_wav, format="wav")

# ---- vocals (start AFTER intro) ----
def espeak_to_wav(text, wav_path, speed=155, pitch=52, voice="en-us"):
    safe = text.replace('"','')
    cmd = f'espeak-ng -v {voice} -s {speed} -p {pitch} -a 135 --stdout "{safe}" | ffmpeg -y -i pipe:0 -ar {SR} -ac 1 "{wav_path}"'
    subprocess.run(["bash","-lc", cmd], check=True)

def speak_fit_to_slot(text, wav_path, slot_ms, base_speed=150, max_speed=210, pitch=52):
    # slower base speed now; only speed up if it doesn't fit
    speed = base_speed
    while True:
        espeak_to_wav(text, wav_path, speed=speed, pitch=pitch)
        a = AudioSegment.from_wav(wav_path)
        if len(a) <= slot_ms or speed >= max_speed:
            return a
        speed += 6

slot_ms = int(BARS_PER_LINE * bar_s * 1000)
vocals = AudioSegment.silent(duration=song_ms, frame_rate=SR)

for i, line in enumerate(lyrics_lines):
    wav_path = os.path.join(out_dir, f"line_v5_{i:02d}.wav")
    pitch = 50 + (i % 3) * 2
    a = speak_fit_to_slot(line, wav_path, slot_ms=slot_ms, base_speed=150, pitch=pitch)

    if len(a) < slot_ms:
        a = a + AudioSegment.silent(duration=(slot_ms - len(a)), frame_rate=SR)

    # Place after intro
    pos_ms = int((INTRO_BARS * bar_s * 1000) + i * slot_ms)
    vocals = vocals.overlay(a - 2, position=pos_ms)

# vocal FX
vocals_wav = os.path.join(out_dir, "vocals_v5_raw.wav")
vocals.export(vocals_wav, format="wav")

vocals_fx_wav = os.path.join(out_dir, "vocals_v5_fx.wav")
subprocess.run([
    "bash","-lc",
    f'ffmpeg -y -i "{vocals_wav}" -af "highpass=f=170, lowpass=f=3800, acompressor=threshold=-18dB:ratio=3:attack=10:release=100" "{vocals_fx_wav}"'
], check=True)

vocals_fx = AudioSegment.from_wav(vocals_fx_wav)

# final
final = instrumental.overlay(vocals_fx, position=0)
final_wav = os.path.join(out_dir, "rap_song_final_v5.wav")
final_mp3 = os.path.join(out_dir, "rap_song_final_v5.mp3")

final.export(final_wav, format="wav")
subprocess.run(["bash","-lc", f'ffmpeg -y -i "{final_wav}" -codec:a libmp3lame -qscale:a 2 "{final_mp3}" >/dev/null'], check=False)

print("✅ Done. Files:")
print(final_wav)
print(final_mp3)
display(Audio(final_wav))

# =========================
# RAP STORY (Spanish translation) — ONE CELL (NO REGISTRATION)
# - Beat urbano chill + bajo + pad
# - Intro ~10s (sin voz) + Outro ~10s (sin voz)
# - Voz neural en español con Edge-TTS (online, sin registro)
# - Más rápido que antes: SLOW_FACTOR = 1.08 (ajusta 1.00–1.15)
# Outputs:
#  /mnt/data/rap_story_es/rap_story_es.wav
#  /mnt/data/rap_story_es/rap_story_es.mp3
# =========================

import os, subprocess
import numpy as np
from scipy.signal import butter, lfilter
from pydub import AudioSegment
from IPython.display import Audio, display

# installs
subprocess.run(["bash","-lc","apt-get -y update >/dev/null && apt-get -y install ffmpeg >/dev/null"], check=False)
subprocess.run(["bash","-lc","pip -q install --upgrade pip setuptools wheel"], check=False)
subprocess.run(["bash","-lc","pip -q install numpy scipy pydub edge-tts nest_asyncio"], check=False)

import edge_tts, nest_asyncio
nest_asyncio.apply()

# ------------------ SETTINGS ------------------
SR = 44100
BPM = 90
BEATS_PER_BAR = 4

INTRO_BARS = 4      # ~10.66s
OUTRO_BARS  = 4     # ~10.66s
BARS_PER_LINE = 4   # mucho espacio para que termine cada bloque

# Faster than previous (less slow-down)
SLOW_FACTOR = 1.08  # 1.00 = normal, 1.08 = un poco más lento, 1.15 = más lento

VOICE = "es-ES-AlvaroNeural"   # masculina (prueba también "es-ES-ElviraNeural")

# Direct translation (natural but faithful) of your English story
lyrics_lines = [
    "Entramos estresados, tú respondiste rápido, yo respondí de vuelta, y el cuarto se puso frío. "
    "Yo me sentí faltado de respeto, tú te sentiste invisible, y los dos nos pusimos firmes. "
    "Mi orgullo quiso manejar la conversación, como si quisiera el control total.",

    "Respiré hondo, bajé la voz, y dije: espera, déjame ser claro. "
    "Esto es lo que sentí en ese momento, y por qué me pegó tan cerca. "
    "Y luego te pregunté con calma: ¿qué estabas necesitando aquí, ahora?",

    "Tú dijiste: me sentí ignorado por semanas, como si mi esfuerzo no contara. "
    "Yo dije: te escucho, y lo siento, puedo ver lo que eso significa. "
    "Pusimos el problema sobre la mesa, no nuestros nombres, no nuestras cuentas.",

    "Hicimos dos opciones, después tres, elegimos la que nos servía a los dos. "
    "Pusimos un límite: nada de ataques, y una promesa: seguir creciendo. "
    "Y si se calienta, pausamos diez minutos, y volvemos, sin desaparecer.",

    "Ahora el mismo cuarto se siente más liviano, como si el aire tuviera una forma nueva. "
    "El conflicto no rompió el vínculo, nos enseñó cómo salir adelante. "
    "La paz no es silencio: es respeto valiente, y la paciencia para reparar."
]

NUM_LINES = len(lyrics_lines)

# ------------------ TIME ------------------
beat_s = 60.0 / BPM
bar_s  = beat_s * BEATS_PER_BAR
slot_ms = int(BARS_PER_LINE * bar_s * 1000)

VOCAL_BARS = NUM_LINES * BARS_PER_LINE
TOTAL_BARS = INTRO_BARS + VOCAL_BARS + OUTRO_BARS
song_ms = int(TOTAL_BARS * bar_s * 1000)

out_dir = "/mnt/data/rap_story_es"
os.makedirs(out_dir, exist_ok=True)

# ------------------ AUDIO HELPERS ------------------
def env_exp(n, decay=0.03, sr=SR):
    t = np.arange(n)/sr
    return np.exp(-t/decay)

def lowpass(x, cutoff=8000, sr=SR, order=4):
    b,a = butter(order, cutoff/(sr/2), btype="low")
    return lfilter(b,a,x)

def highpass(x, cutoff=200, sr=SR, order=4):
    b,a = butter(order, cutoff/(sr/2), btype="high")
    return lfilter(b,a,x)

def sine(freq, dur_s, amp=0.6, sr=SR):
    n = int(dur_s*sr)
    t = np.arange(n)/sr
    return (amp*np.sin(2*np.pi*freq*t)).astype(np.float32)

def noise(dur_s, amp=0.4, sr=SR):
    n = int(dur_s*sr)
    return (amp*np.random.uniform(-1,1,n)).astype(np.float32)

def normalize(x, target=0.95):
    m = np.max(np.abs(x)) + 1e-9
    return (x/m*target).astype(np.float32)

def to_audiosegment(x, sr=SR):
    x = np.clip(x, -1, 1)
    pcm = (x * 32767).astype(np.int16).tobytes()
    return AudioSegment(data=pcm, sample_width=2, frame_rate=sr, channels=1)

def overlay(base: AudioSegment, layer: AudioSegment, position_ms=0, gain_db=0.0):
    return base.overlay(layer + gain_db, position=position_ms)

def ms(t_s): return int(t_s*1000)

def slow_down(audio: AudioSegment, factor: float):
    # factor > 1 => más lento; factor cercano a 1 => más rápido
    new_rate = int(audio.frame_rate / factor)
    return audio._spawn(audio.raw_data, overrides={"frame_rate": new_rate}).set_frame_rate(SR)

# ------------------ DRUM SYNTH ------------------
def kick():
    dur = 0.18
    n = int(dur*SR)
    t = np.arange(n)/SR
    f0, f1 = 90.0, 45.0
    f = f0 * (f1/f0) ** (t/dur)
    phase = 2*np.pi*np.cumsum(f)/SR
    x = np.sin(phase) * env_exp(n, decay=0.07)
    x = lowpass(x, cutoff=900)
    return normalize(x, 0.9)

def snare():
    dur = 0.15
    n = int(dur*SR)
    x = noise(dur, amp=0.8)
    x = highpass(x, cutoff=1200)
    x = x * env_exp(n, decay=0.05)
    x += sine(180, dur, amp=0.15) * env_exp(n, decay=0.05)
    return normalize(x, 0.8)

def hat():
    dur = 0.06
    n = int(dur*SR)
    x = noise(dur, amp=0.35)
    x = highpass(x, cutoff=6000)
    x = x * env_exp(n, decay=0.02)
    return normalize(x, 0.5)

KICK = to_audiosegment(kick())
SNARE = to_audiosegment(snare())
HAT = to_audiosegment(hat())

# ------------------ DRUMS TRACK ------------------
drums = AudioSegment.silent(duration=song_ms, frame_rate=SR)
for bar in range(TOTAL_BARS):
    bar_start = bar * bar_s
    kicks = [0.0, 2.0] + ([3.5] if bar % 2 == 1 else [])
    for b in kicks:
        drums = overlay(drums, KICK, position_ms=ms(bar_start + b*beat_s), gain_db=0)
    for b in [1.0, 3.0]:
        drums = overlay(drums, SNARE, position_ms=ms(bar_start + b*beat_s), gain_db=-1)
    for i in range(8):
        b = i * 0.5
        gain = -6 if (i % 2 == 0) else -8
        drums = overlay(drums, HAT, position_ms=ms(bar_start + b*beat_s), gain_db=gain)

# ------------------ BASS + PAD ------------------
def note_freq(midi_note):
    return 440.0 * (2 ** ((midi_note - 69)/12))

bass_roots = [45, 41, 43, 40]  # A2 F2 G2 E2
chords = [
    [57, 60, 64],  # Am
    [53, 57, 60],  # F
    [55, 59, 62],  # G
    [52, 55, 59],  # Em-ish
]

def bass_hit(freq, dur_s, amp=0.6):
    x = sine(freq, dur_s, amp=amp)
    x = lowpass(x, cutoff=250)
    x *= env_exp(len(x), decay=0.12)
    return x.astype(np.float32)

def chord_pad(freqs, dur_s, amp=0.18):
    n = int(dur_s*SR)
    t = np.arange(n)/SR
    x = np.zeros(n, dtype=np.float32)
    for f in freqs:
        for k, a in [(1,1.0),(2,0.35),(3,0.2)]:
            x += (amp*a)*np.sin(2*np.pi*(f*k)*t)
    x = lowpass(x, cutoff=1800)
    fade = np.ones(n, dtype=np.float32)
    fi = int(0.08*n); fo = int(0.12*n)
    fade[:fi] = np.linspace(0,1,fi)
    fade[-fo:] = np.linspace(1,0,fo)
    x *= fade
    return normalize(x, 0.6)

inst = AudioSegment.silent(duration=song_ms, frame_rate=SR)
for bar in range(TOTAL_BARS):
    idx = bar % 4
    root = bass_roots[idx]
    chord = chords[idx]

    b1 = bass_hit(note_freq(root), beat_s*0.6, amp=0.65)
    b3 = bass_hit(note_freq(root), beat_s*0.6, amp=0.60)

    bass_seg = AudioSegment.silent(duration=int(bar_s*1000), frame_rate=SR)
    bass_seg = overlay(bass_seg, to_audiosegment(b1), position_ms=0, gain_db=-1)
    bass_seg = overlay(bass_seg, to_audiosegment(b3), position_ms=ms(2*beat_s), gain_db=-1)

    freqs = [note_freq(n) for n in chord]
    pad_seg = to_audiosegment(chord_pad(freqs, bar_s, amp=0.14))

    bar_seg = AudioSegment.silent(duration=int(bar_s*1000), frame_rate=SR)
    bar_seg = overlay(bar_seg, pad_seg, position_ms=0, gain_db=-9)
    bar_seg = overlay(bar_seg, bass_seg, position_ms=0, gain_db=0)

    inst = overlay(inst, bar_seg, position_ms=ms(bar*bar_s), gain_db=0)

instrumental = inst.overlay(drums, position=0) - 1
instrumental_path = os.path.join(out_dir, "instrumental.wav")
instrumental.export(instrumental_path, format="wav")

# ------------------ EDGE-TTS (NEURAL) ------------------
async def synth_to_mp3(text, mp3_path):
    communicate = edge_tts.Communicate(text=text, voice=VOICE)
    await communicate.save(mp3_path)

async def synth_all():
    # secuencial para evitar problemas de red
    for i, text in enumerate(lyrics_lines):
        mp3_path = os.path.join(out_dir, f"line_{i:02d}.mp3")
        await synth_to_mp3(text, mp3_path)

await synth_all()

# ------------------ BUILD VOCALS TRACK ------------------
vocals = AudioSegment.silent(duration=song_ms, frame_rate=SR)

for i in range(NUM_LINES):
    mp3_path = os.path.join(out_dir, f"line_{i:02d}.mp3")
    a = AudioSegment.from_file(mp3_path).set_frame_rate(SR).set_channels(1)
    a = slow_down(a, factor=SLOW_FACTOR)  # closer to 1 => faster

    # fit inside slot
    if len(a) < slot_ms:
        a = a + AudioSegment.silent(duration=(slot_ms - len(a)), frame_rate=SR)
    else:
        a = a[:slot_ms]

    pos_ms = int((INTRO_BARS * bar_s * 1000) + i * slot_ms)
    vocals = vocals.overlay(a - 3, position=pos_ms)

# vocal FX (soft)
vocals_raw = os.path.join(out_dir, "vocals_raw.wav")
vocals.export(vocals_raw, format="wav")

vocals_fx = os.path.join(out_dir, "vocals_fx.wav")
subprocess.run(
    ["bash","-lc", f'ffmpeg -y -i "{vocals_raw}" -af "highpass=f=120, lowpass=f=8000, acompressor=threshold=-20dB:ratio=3:attack=10:release=140" "{vocals_fx}"'],
    check=True
)
vocals_fx_seg = AudioSegment.from_wav(vocals_fx)

# ------------------ FINAL MIX ------------------
final = instrumental.overlay(vocals_fx_seg, position=0)

final_wav = os.path.join(out_dir, "rap_story_es.wav")
final_mp3 = os.path.join(out_dir, "rap_story_es.mp3")

final.export(final_wav, format="wav")
subprocess.run(["bash","-lc", f'ffmpeg -y -i "{final_wav}" -codec:a libmp3lame -qscale:a 2 "{final_mp3}" >/dev/null'], check=False)

print("✅ Done. Files:")
print(final_wav)
print(final_mp3)
display(Audio(final_wav))

# ============================================
# ORIGINAL Progressive Rock Instrumental (fast solos) — ONE-CELL COLAB
# - No registration
# - Generates a brand-new MIDI + renders to WAV/MP3 using FluidSynth + free GM soundfont
# Outputs:
#   /mnt/data/prog_rock_original/prog_rock_original.mid
#   /mnt/data/prog_rock_original/prog_rock_original.wav
#   /mnt/data/prog_rock_original/prog_rock_original.mp3
# ============================================

import os, random, math, subprocess
import numpy as np

# ---- installs (Colab) ----
subprocess.run(["bash","-lc","apt-get -y update >/dev/null && apt-get -y install fluidsynth ffmpeg fluid-soundfont-gm >/dev/null"], check=False)
subprocess.run(["bash","-lc","pip -q install pretty_midi"], check=False)

import pretty_midi
from IPython.display import Audio, display

out_dir = "/mnt/data/prog_rock_original"
os.makedirs(out_dir, exist_ok=True)

# ----------------------------
# MUSIC SETTINGS
# ----------------------------
random.seed(7)
np.random.seed(7)

TEMPO = 160  # fast prog-rock feel
pm = pretty_midi.PrettyMIDI(initial_tempo=TEMPO)

# GM programs
PROG_LEAD   = 29  # Overdriven Guitar
PROG_RHYTHM = 30  # Distortion Guitar
PROG_BASS   = 34  # Electric Bass (finger)

# Drums use is_drum=True
lead   = pretty_midi.Instrument(program=PROG_LEAD,   name="Lead Guitar")
rhythm = pretty_midi.Instrument(program=PROG_RHYTHM, name="Rhythm Guitar")
bass   = pretty_midi.Instrument(program=PROG_BASS,   name="Bass")
drums  = pretty_midi.Instrument(program=0, is_drum=True, name="Drums")

pm.instruments.extend([rhythm, lead, bass, drums])

# ----------------------------
# HELPERS
# ----------------------------
def bt(beat):  # beats -> seconds
    return (60.0 / TEMPO) * beat

def add_note(inst, pitch, start_beat, dur_beat, vel=100):
    n = pretty_midi.Note(
        velocity=int(np.clip(vel, 1, 127)),
        pitch=int(np.clip(pitch, 0, 127)),
        start=bt(start_beat),
        end=bt(start_beat + dur_beat),
    )
    inst.notes.append(n)

def add_chord(inst, pitches, start_beat, dur_beat, vel=95, strum=0.0):
    # optional tiny strum in beats
    for i, p in enumerate(pitches):
        add_note(inst, p, start_beat + i*strum, dur_beat - i*strum, vel)

def add_drums_4_4(start_beat, bars, intensity=1.0):
    # Kick=36, Snare=38, HH closed=42, Crash=49, Ride=51, Tom=45/47
    beat = start_beat
    for _ in range(bars):
        # crash on bar start sometimes
        if random.random() < 0.35:
            add_note(drums, 49, beat, 0.25, vel=int(95*intensity))
        # 8th hats
        for i in range(8):
            add_note(drums, 42, beat + i*0.5, 0.15, vel=int((65 if i%2==0 else 55)*intensity))
        # backbeat
        add_note(drums, 38, beat + 1.0, 0.2, vel=int(100*intensity))
        add_note(drums, 38, beat + 3.0, 0.2, vel=int(100*intensity))
        # kick pattern (syncopated)
        for k in [0.0, 1.5, 2.0, 2.75]:
            add_note(drums, 36, beat + k, 0.18, vel=int(105*intensity))
        beat += 4.0

def add_drums_7_8(start_beat, bars, intensity=1.0):
    # 7/8 = 3.5 beats if beat = quarter-note
    beat = start_beat
    for _ in range(bars):
        if random.random() < 0.4:
            add_note(drums, 49, beat, 0.25, vel=int(92*intensity))
        # hats in 8ths -> 7 eighths = 3.5 beats => steps of 0.5, total 7 hits
        for i in range(7):
            add_note(drums, 42, beat + i*0.5, 0.13, vel=int((62 if i%2==0 else 52)*intensity))
        # snare accents (grouping 2+2+3 eighths)
        add_note(drums, 38, beat + 1.0, 0.2, vel=int(95*intensity))
        add_note(drums, 38, beat + 2.0, 0.2, vel=int(90*intensity))
        # kick accents
        for k in [0.0, 1.5, 2.5, 3.0]:
            add_note(drums, 36, beat + k, 0.18, vel=int(102*intensity))
        beat += 3.5

def palm_mute_riff(root_pitch, start_beat, bars_7_8):
    # chuggy riff in 7/8 using E minor-ish powerchords, octave jumps
    beat = start_beat
    for _ in range(bars_7_8):
        # 7/8 = 7 eighths
        pattern = [0,0,7,0,5,0,3]  # offsets in semitones relative to root
        for i, off in enumerate(pattern):
            dur = 0.25 if i in [0,1,3,5] else 0.5  # chugs short, accents longer
            pitch = root_pitch + off
            # powerchord (root + fifth) on accents
            if i in [2,4,6]:
                add_chord(rhythm, [pitch, pitch+7], beat + i*0.5, 0.48, vel=110, strum=0.01)
                add_note(bass, pitch-12, beat + i*0.5, 0.48, vel=105)
            else:
                add_note(rhythm, pitch, beat + i*0.5, dur, vel=88)
                add_note(bass, pitch-12, beat + i*0.5, dur, vel=92)
        beat += 3.5
    return beat

def prog_chords_section(start_beat, bars):
    # original progression (E minor with colors): Em9 -> Cmaj7 -> Dadd9 -> B7#9
    # 1 bar each in 4/4
    beat = start_beat
    prog = [
        [52, 55, 59, 62, 66],  # Em9 (E3 G3 B3 D4 F#4)
        [48, 52, 55, 59],      # Cmaj7 (C3 E3 G3 B3)
        [50, 54, 57, 62],      # Dadd9 (D3 F#3 A3 E4)
        [47, 51, 55, 58, 62],  # B7#9-ish voicing (B2 D#3 F#3 A3 C#4)
    ]
    for i in range(bars):
        chord = prog[i % len(prog)]
        add_chord(rhythm, chord, beat, 4.0, vel=92, strum=0.02)
        # bass follows roots with movement
        root = chord[0]
        add_note(bass, root-12, beat, 1.0, vel=100)
        add_note(bass, root-12+7, beat+1.0, 0.5, vel=90)
        add_note(bass, root-12+5, beat+1.5, 0.5, vel=90)
        add_note(bass, root-12, beat+2.0, 1.0, vel=98)
        add_note(bass, root-12+2, beat+3.0, 1.0, vel=92)
        beat += 4.0
    return beat

def fast_solo(start_beat, bars):
    # Fast melodic solo in E Dorian / E minor pentatonic mix, 16th-note runs
    beat = start_beat
    # scales around E4-E6
    e_dorian = [64,66,67,69,71,73,74,76]  # E4..E5 dorian
    pent     = [64,67,69,71,74,76]        # E minor pent
    for b in range(bars):
        # 16ths: 16 notes per bar in 4/4
        t = beat
        for i in range(16):
            src = e_dorian if (b % 2 == 0) else pent
            p = random.choice(src) + (12 if random.random()<0.55 else 0)  # jump up octave often
            # phrase shaping
            vel = 105 if i in [0,4,8,12] else 92
            add_note(lead, p, t, 0.25, vel=vel)
            t += 0.25
        # add a held "scream" note at end of every 2 bars
        if b % 2 == 1:
            end_note = 88 if random.random()<0.5 else 90  # E6/F#6-ish
            add_note(lead, end_note, beat+3.0, 1.0, vel=118)
        beat += 4.0
    return beat

def ending_tag(start_beat, bars):
    beat = start_beat
    for _ in range(bars):
        # rhythmic stabs
        for k in [0.0, 1.0, 2.0, 3.0]:
            add_chord(rhythm, [52,59,64], beat+k, 0.35, vel=110, strum=0.01)  # E5-ish
            add_note(bass, 40, beat+k, 0.35, vel=110)  # E2
        beat += 4.0
    # final hit + ring
    add_chord(rhythm, [52,59,64,67], beat, 3.5, vel=118, strum=0.02)
    add_note(bass, 40, beat, 3.5, vel=118)
    add_note(drums, 49, beat, 0.25, vel=120)  # crash
    return beat + 3.5

# ----------------------------
# ARRANGEMENT (Original)
# ----------------------------
cur = 0.0

# A) 7/8 intro riff (8 bars)
add_drums_7_8(cur, bars=8, intensity=0.95)
cur = palm_mute_riff(root_pitch=52, start_beat=cur, bars_7_8=8)  # E3 root

# B) 4/4 chord section (8 bars)
add_drums_4_4(cur, bars=8, intensity=1.00)
cur = prog_chords_section(cur, bars=8)

# C) Pre-solo build (4 bars, heavier rhythm)
add_drums_4_4(cur, bars=4, intensity=1.12)
# tighter powerchords on each beat
for i in range(4):
    add_chord(rhythm, [52,59], cur+i*4.0+0.0, 4.0, vel=115, strum=0.01) # E5
    add_note(bass, 40, cur+i*4.0, 4.0, vel=110)
cur += 16.0

# D) Solo (12 bars fast)
add_drums_4_4(cur, bars=12, intensity=1.15)
# rhythm under solo: alternating Em / D / C / B stabs
roots = [52,50,48,47]
for i in range(12):
    r = roots[i % 4]
    add_chord(rhythm, [r, r+7, r+12], cur+i*4.0, 4.0, vel=90, strum=0.02)
    add_note(bass, r-12, cur+i*4.0, 1.0, vel=98)
    add_note(bass, r-12, cur+i*4.0+2.0, 1.0, vel=95)
cur = fast_solo(cur, bars=12)

# E) Return to 7/8 riff (4 bars)
add_drums_7_8(cur, bars=4, intensity=1.05)
cur = palm_mute_riff(root_pitch=52, start_beat=cur, bars_7_8=4)

# F) Big ending (4 bars + final ring)
add_drums_4_4(cur, bars=4, intensity=1.20)
cur = ending_tag(cur, bars=4)

# ----------------------------
# WRITE MIDI
# ----------------------------
midi_path = os.path.join(out_dir, "prog_rock_original.mid")
pm.write(midi_path)

# ----------------------------
# RENDER AUDIO with FluidSynth
# ----------------------------
sf2_candidates = [
    "/usr/share/sounds/sf2/FluidR3_GM.sf2",
    "/usr/share/sounds/sf2/FluidR3_GM2-2.sf2",
    "/usr/share/sounds/sf2/FluidR3_GM2.sf2",
]
sf2 = next((p for p in sf2_candidates if os.path.exists(p)), None)
if sf2 is None:
    raise FileNotFoundError("No GM soundfont found. (fluid-soundfont-gm install may have failed)")

wav_path = os.path.join(out_dir, "prog_rock_original.wav")
mp3_path = os.path.join(out_dir, "prog_rock_original.mp3")

subprocess.run(["bash","-lc", f'fluidsynth -ni "{sf2}" "{midi_path}" -F "{wav_path}" -r {SR} >/dev/null'], check=True)
subprocess.run(["bash","-lc", f'ffmpeg -y -i "{wav_path}" -codec:a libmp3lame -qscale:a 2 "{mp3_path}" >/dev/null'], check=False)

print("✅ Done. Files:")
print(midi_path)
print(wav_path)
print(mp3_path)

display(Audio(wav_path))

# =========================
# KIDS SONG v4 — Edge TTS (Python) + nest_asyncio ✅ (no CLI, no event-loop crash)
# Original children’s pop vibe + JennyNeural chant vocals (NO SSML)
# Outputs: /mnt/data/kids_song_project/kids_song_final.wav and .mp3
# =========================

import os, subprocess, random
import numpy as np
from scipy.signal import butter, lfilter
from pydub import AudioSegment
from IPython.display import Audio, display

subprocess.run(["bash","-lc","apt-get -y update >/dev/null && apt-get -y install ffmpeg >/dev/null"], check=False)
subprocess.run(["bash","-lc","pip -q install edge-tts nest_asyncio numpy scipy pydub"], check=False)

import edge_tts, asyncio, nest_asyncio
nest_asyncio.apply()

SR = 44100
BPM = 120
BEAT_S = 60.0 / BPM
BAR_S = 4 * BEAT_S

out_dir = "/mnt/data/kids_song_project"
os.makedirs(out_dir, exist_ok=True)

INST_WAV  = os.path.join(out_dir, "instrumental.wav")
FINAL_WAV = os.path.join(out_dir, "kids_song_final.wav")
FINAL_MP3 = os.path.join(out_dir, "kids_song_final.mp3")

# -------- Voice (same as meditation) --------
VOICE_NAME = "es-MX-DaliaNeural"
RATE = "+15%"      # energetic
PITCH_BASE = "+7Hz" # try "+6Hz" for more kid-like

# -------- Lyrics (your original + extra kid-play lines) --------
INTRO_BARS = 4
OUTRO_BARS = 4

verse1 = [
    "John, y Michael están jugando con los juguetes.",
    "Y en la cocina con la abuela Britney vamos a armar un puzzle con Caroline.",
    "Y con la abuela Britney vamos a armar una tartaleta.",
    "Vamos a armar, vamos a armar, vamos a armar.",
    "Y recortar.",
]
chorus = [
    "Vamos a armar, vamos a armar, vamos a armar.",
    "Y recortar, y recortar, y recortar.",
    "Uno, dos, tres, a jugar.",
]
verse2 = [
    "Busco la pieza, la encuentro, la pongo, y hago un aplauso.",
    "Si me equivoco, no pasa nada, lo intento de nuevo despacio.",
    "Jugando juntitas, con la abuela Britney, todo se hace más fácil.",
]
bridge = [
    "Respiro suave, me calmo un poquito.",
    "Cambio el pensamiento: yo sí puedo, lo logro solito.",
    "Sigo jugando, y sigo intentándolo, paso a pasito.",
]

sections = [
    ("VERSE", verse1),
    ("CHORUS", chorus),
    ("VERSE", verse2),
    ("CHORUS", chorus),
    ("BRIDGE", bridge),
    ("CHORUS", chorus),
]

BARS_PER_LINE = 2
LINE_SLOT_MS = int(BARS_PER_LINE * BAR_S * 1000)

num_lines = sum(len(lines) for _, lines in sections)
VOCAL_BARS = num_lines * BARS_PER_LINE
TOTAL_BARS = INTRO_BARS + VOCAL_BARS + OUTRO_BARS
SONG_MS = int(TOTAL_BARS * BAR_S * 1000)

# -------- Helpers (audio synth) --------
def lowpass(x, cutoff=8000, sr=SR, order=4):
    b, a = butter(order, cutoff/(sr/2), btype="low")
    return lfilter(b, a, x)

def highpass(x, cutoff=200, sr=SR, order=4):
    b, a = butter(order, cutoff/(sr/2), btype="high")
    return lfilter(b, a, x)

def env_exp(n, decay=0.06, sr=SR):
    t = np.arange(n)/sr
    return np.exp(-t/decay)

def sine(freq, dur_s, amp=0.6, sr=SR):
    n = int(dur_s*sr)
    t = np.arange(n)/sr
    return (amp*np.sin(2*np.pi*freq*t)).astype(np.float32)

def noise(dur_s, amp=0.4, sr=SR):
    n = int(dur_s*sr)
    return (amp*np.random.uniform(-1,1,n)).astype(np.float32)

def normalize(x, target=0.95):
    m = np.max(np.abs(x)) + 1e-9
    return (x/m*target).astype(np.float32)

def to_audiosegment_mono(x, sr=SR):
    x = np.clip(x, -1, 1)
    pcm = (x * 32767).astype(np.int16).tobytes()
    return AudioSegment(data=pcm, sample_width=2, frame_rate=sr, channels=1)

def overlay(base: AudioSegment, layer: AudioSegment, position_ms=0, gain_db=0.0):
    return base.overlay(layer + gain_db, position=position_ms)

def ms(t_s): return int(t_s*1000)

# -------- Drums --------
def kick():
    dur = 0.16
    n = int(dur*SR)
    t = np.arange(n)/SR
    f0, f1 = 110.0, 55.0
    f = f0 * (f1/f0) ** (t/dur)
    phase = 2*np.pi*np.cumsum(f)/SR
    x = np.sin(phase) * env_exp(n, decay=0.08)
    x = lowpass(x, cutoff=900)
    return normalize(x, 0.85)

def clap():
    dur = 0.12
    x = noise(dur, amp=0.9)
    x = highpass(x, cutoff=1200)
    x = x * env_exp(len(x), decay=0.04)
    return normalize(x, 0.65)

def shaker():
    dur = 0.05
    x = noise(dur, amp=0.25)
    x = highpass(x, cutoff=6000)
    x = x * env_exp(len(x), decay=0.02)
    return normalize(x, 0.45)

KICK = to_audiosegment_mono(kick())
CLAP = to_audiosegment_mono(clap())
SHAK = to_audiosegment_mono(shaker())

def midi_to_freq(m):
    return 440.0 * (2 ** ((m - 69)/12))

# C - G - Am - F
roots = [48, 43, 45, 41]
chords = [
    [60, 64, 67],
    [59, 62, 67],
    [57, 60, 64],
    [57, 60, 65],
]

def pluck(freq, dur_s, amp=0.25):
    n = int(dur_s*SR)
    t = np.arange(n)/SR
    x = (np.sin(2*np.pi*freq*t) +
         0.35*np.sin(2*np.pi*freq*2*t) +
         0.20*np.sin(2*np.pi*freq*3*t)).astype(np.float32)
    x *= env_exp(n, decay=0.06)
    x = lowpass(x, cutoff=4200)
    return normalize(x, target=0.7) * amp

def bass(freq, dur_s, amp=0.35):
    x = sine(freq, dur_s, amp=amp)
    x = lowpass(x, cutoff=220)
    x *= env_exp(len(x), decay=0.12)
    return x.astype(np.float32)

# -------- Build instrumental --------
inst = AudioSegment.silent(duration=SONG_MS, frame_rate=SR)

for bar in range(TOTAL_BARS):
    bar_start_s = bar * BAR_S
    idx = bar % 4
    chord_midis = chords[idx]
    root = roots[idx]

    inst = overlay(inst, KICK, position_ms=ms(bar_start_s + 0*BEAT_S), gain_db=-1)
    inst = overlay(inst, KICK, position_ms=ms(bar_start_s + 2*BEAT_S), gain_db=-2)

    inst = overlay(inst, CLAP, position_ms=ms(bar_start_s + 1*BEAT_S), gain_db=-4)
    inst = overlay(inst, CLAP, position_ms=ms(bar_start_s + 3*BEAT_S), gain_db=-4)

    for i in range(8):
        inst = overlay(inst, SHAK, position_ms=ms(bar_start_s + i*0.5*BEAT_S), gain_db=-12)

    b1 = to_audiosegment_mono(bass(midi_to_freq(root), 0.45, amp=0.45))
    b3 = to_audiosegment_mono(bass(midi_to_freq(root), 0.45, amp=0.42))
    inst = overlay(inst, b1, position_ms=ms(bar_start_s + 0*BEAT_S), gain_db=-2)
    inst = overlay(inst, b3, position_ms=ms(bar_start_s + 2*BEAT_S), gain_db=-2)

    freqs = [midi_to_freq(m) for m in chord_midis]
    for beat in [0.0, 1.0, 2.0, 3.0]:
        f = random.choice(freqs)
        p = to_audiosegment_mono(pluck(f, 0.18, amp=0.22))
        inst = overlay(inst, p, position_ms=ms(bar_start_s + beat*BEAT_S), gain_db=-10)

inst = inst.apply_gain(-2).fade_in(800).fade_out(1200)
inst.export(INST_WAV, format="wav")

# -------- Vocals (Edge TTS Python, no SSML) --------
async def tts_line_to_wav(text, wav_out, pitch):
    tmp_mp3 = wav_out.replace(".wav", ".mp3")
    comm = edge_tts.Communicate(text=text, voice=VOICE_NAME, rate=RATE, pitch=pitch)
    await comm.save(tmp_mp3)
    subprocess.run(["bash","-lc", f'ffmpeg -y -loglevel error -i "{tmp_mp3}" -ar {SR} -ac 1 "{wav_out}"'], check=False)

async def build_vocals_async():
    vocals = AudioSegment.silent(duration=SONG_MS, frame_rate=SR)
    start_ms = int(INTRO_BARS * BAR_S * 1000)
    line_index = 0

    for _, lines in sections:
        for line in lines:
            wav_i = os.path.join(out_dir, f"line_{line_index:02d}.wav")
            # small pitch variation for “singy” feel
            pitch = "+3Hz" if (line_index % 3 == 0) else ("-2Hz" if (line_index % 3 == 1) else PITCH_BASE)
            await tts_line_to_wav(line, wav_i, pitch=pitch)

            a = AudioSegment.from_wav(wav_i)
            if len(a) > LINE_SLOT_MS:
                a = a[:LINE_SLOT_MS]
            else:
                a = a + AudioSegment.silent(duration=(LINE_SLOT_MS - len(a)), frame_rate=SR)

            pos = start_ms + line_index * LINE_SLOT_MS
            vocals = vocals.overlay(a - 1, position=pos)
            line_index += 1

    # light cleanup
    vocals_raw = os.path.join(out_dir, "vocals_raw.wav")
    vocals.export(vocals_raw, format="wav")
    vocals_fx = os.path.join(out_dir, "vocals_fx.wav")
    subprocess.run(["bash","-lc",
        f'ffmpeg -y -loglevel error -i "{vocals_raw}" '
        f'-af "highpass=f=120, lowpass=f=6500, acompressor=threshold=-18dB:ratio=2.5:attack=10:release=120" '
        f'"{vocals_fx}"'
    ], check=False)
    return AudioSegment.from_wav(vocals_fx)

# Run async safely inside notebook (nest_asyncio makes this re-entrant)
loop = asyncio.get_event_loop()
vocals = loop.run_until_complete(build_vocals_async())

# -------- Final mix --------
instrumental = AudioSegment.from_wav(INST_WAV)
final = instrumental.overlay(vocals, position=0).fade_in(800).fade_out(1200)

final.export(FINAL_WAV, format="wav")
subprocess.run(["bash","-lc", f'ffmpeg -y -loglevel error -i "{FINAL_WAV}" -codec:a libmp3lame -qscale:a 2 "{FINAL_MP3}"'], check=False)

print("✅ Done. Files:")
print(FINAL_WAV)
print(FINAL_MP3)
display(Audio(FINAL_WAV))